Fix VALIDTOKEN REREGTOKEN

diff --git a/diclish b/diclish
--- a/diclish
+++ b/diclish
@@ -16,8 +16,9 @@
 #
 #
 # License: WTFPL2 http://wtfpl2.com/
+# uzver(at)protonmail.ch
 #
-# Deps: curl, jq, grep, sed, awk, tr, mkdir, mktemp
+# Deps: curl, jq, grep, sed, awk, tr, mkdir, mktemp, rm, wc
 
 
 dotdir="${HOME}/.diclish"
@@ -172,6 +173,7 @@ TOKENS(){
   idtoken=$(echo "$tempauth"|awk -F'id_token":"' '{print $2}'|awk -F'"' '{print $1}') && echo "idtoken=\"$idtoken\"">>"$config"
   ! (($quiet)) && (($verbose)) && echo -e "\e[0;36m""idtoken = $idtoken""\e[m\n"
   unset tempauth
+  unset csrf authtoken authcode accesstoken
 }
 
 REREGTOKENS(){
@@ -179,43 +181,45 @@ REREGTOKENS(){
   source "$config"
   cookie="${dotdir}/${handle}.cookie"
   [[ -f "$cookie" ]] || (touch "$cookie" && chmod 600 "$cookie")
-  tempfile=$(mktemp /tmp/pwtemp.XXXXXX)
-  chmod 600 "$tempfile"
-  curl -ks -H "User-Agent: $useragent" "${pod}"/api/openid_connect/clients -d "redirect_uris[]=${pod}/&client_name=$clientname" >"$tempfile"
-  clientid=$(cat "$tempfile" | awk -F'client_id":"' '{print $2}' | awk -F'"' '{print $1}')
-  clientsecret=$(cat "$tempfile" | awk -F'client_secret":"' '{print $2}' | awk -F'"' '{print $1}')
-  if ! (($quiet)) && (($verbose)); then
-	echo -e "\e[0;36m""clientid = $clientid""\e[m\n"
-	echo -e "\e[0;36m""clientsecret = $clientsecret""\e[m\n"
-  fi
+  # tempfile=$(mktemp /tmp/pwtemp.XXXXXX)
+  # chmod 600 "$tempfile"
+  # curl -ks -H "User-Agent: $useragent" "${pod}"/api/openid_connect/clients -d "redirect_uris[]=${pod}/&client_name=$clientname" >"$tempfile"
+  # clientid=$(cat "$tempfile" | awk -F'client_id":"' '{print $2}' | awk -F'"' '{print $1}')
+  # clientsecret=$(cat "$tempfile" | awk -F'client_secret":"' '{print $2}' | awk -F'"' '{print $1}')
+  # if ! (($quiet)) && (($verbose)); then
+	# echo -e "\e[0;36m""clientid = $clientid""\e[m\n"
+	# echo -e "\e[0;36m""clientsecret = $clientsecret""\e[m\n"
+  # fi
   csrf=$(curl -ks -H "User-Agent: $useragent" -L "${pod}"/api/openid_connect/authorizations/new?client_id=${clientid}\&redirect_uri=${pod}/\&response_type=code\&scope=openid%20read%20write\&nonce=hi\&state=hi --cookie-jar "$cookie"|tr '\n' ' '|awk -F'block-form' '{print $2}'|awk -F'authenticity_token" value="' '{print $2}'|awk -F'"' '{print $1}')
   ! (($quiet)) && (($verbose)) && echo -e "\e[0;36m""csrf = $csrf""\e[m\n"
-  sed -i '/clientname=/d' "$config"; echo "clientname=\"$clientname\"">>"$config"
-  sed -i '/clientid=/d' "$config"; echo "clientid=\"$clientid\"">>"$config"
-  sed -i '/clientsecret=/d' "$config"; echo "clientsecret=\"$clientsecret\"">>"$config"
-  sed -i '/csrf=/d' "$config"; echo "csrf=\"$csrf\"">>"$config"
-  /bin/rm -f "$tempfile"
+  # [[ "$clientname" ]] && sed -i '/clientname=/d' "$config"; echo "clientname=\"$clientname\"">>"$config"
+  # [[ "$clientid" ]] && sed -i '/clientid=/d' "$config"; echo "clientid=\"$clientid\"">>"$config"
+  # [[ "$clientsecret" ]] && sed -i '/clientsecret=/d' "$config"; echo "clientsecret=\"$clientsecret\"">>"$config"
+  [[ "$csrf" ]] && sed -i '/csrf=/d' "$config"; echo "csrf=\"$csrf\"">>"$config"
+  # /bin/rm -f "$tempfile"
   if ! [[ "$password" ]]; then
 	echo -e '\E[37;34m'"\033[1m[notice]\033[0m" "This will be the only time you will be asked for your password."
 	echo "Your password will be stored plain in config file"
 	PASSWORD
+    ## Store  password in config file:
+    sed -i '/password=/d' "$config"
+    echo password=\"$(sed 's/\"/\\"/g'<<<"$password")\">>"$config"
+    if (($verbose)); then
+      echo -e "\e[0;36m""Password have been saved to $config""\e[m"
+    fi
   fi
-  sed -i '/password=/d' "$config"
-  echo password=\"$(sed 's/\"/\\"/g'<<<"$password")\">>"$config"
-  if (($verbose)); then
-	echo -e "\e[0;36m""Password have been saved to $config""\e[m"
-  fi
+  #'
   authtoken=$(curl -ks -H "User-Agent: $useragent" -L -H "X-CSRF-TOKEN: $csrf" -d "user[username]=${username}&user[password]=${password}&user[remember_me]=1" "${pod}"/users/sign_in --cookie-jar "$cookie" --cookie "$cookie"|tr '\n' ' '|awk -F'authenticity_token" value="' '{print $2}'|awk -F'"' '{print $1}')
-  unset password
   ! (($quiet)) && (($verbose)) && echo -e "\e[0;36m""authtoken = $authtoken""\e[m\n"
   authcode=$(curl -ks -H "User-Agent: $useragent" -H "X-CSRF-TOKEN: $authtoken" -d "approve=true" "${pod}"/api/openid_connect/authorizations --cookie-jar "$cookie" --cookie "$cookie"|awk -F'code=' '{print $2}'|awk -F'"' '{print $1}'|awk -F'&' '{print $1}')
   ! (($quiet)) && (($verbose)) && echo -e "\e[0;36m""authcode = $authcode""\e[m\n"
-  sed -i '/authtoken=/d' "$config"; echo "authtoken=\"$authtoken\"">>"$config"
-  sed -i '/authcode=/d' "$config"; echo "authcode=\"$authcode\"">>"$config"
+  [[ "$authtoken" ]] && sed -i '/authtoken=/d' "$config"; echo "authtoken=\"$authtoken\"">>"$config"
+  [[ "$authcode" ]] && sed -i '/authcode=/d' "$config"; echo "authcode=\"$authcode\"">>"$config"
   source "$config"
   TOKENS
   source "$config"
-  VALIDTOKEN
+  unset password
+  # VALIDTOKEN # Infinity retries
   if [[ "$accesstoken" ]]; then
 	  if ! (($quiet)); then
 		echo -e '\E[37;32m'"\033[1m[success]\033[0m" "Config updated!"
@@ -235,29 +239,29 @@ VALIDTOKEN(){
   if ! (($quiet)) && (($verbose)); then
     echo -e "\e[0;36m""Validating login tokens""\e[m"
   fi
- tmpauth=$(curl -ks -H "User-Agent: $useragent" -H "Authorization: Bearer $accesstoken" "${pod}"/api/openid_connect/user_info)
+  tmpauth=$(curl -ks -H "User-Agent: $useragent" -H "Authorization: Bearer $accesstoken" "${pod}"/api/openid_connect/user_info)
 
-  if [[ "$(echo "$tmpauth"|grep error)" ]]
-  then
+  if [[ "$(echo "$tmpauth"|grep error)" ]]; then
     if ! (($quiet)); then
-      (($verbose)) && echo -e "\e[0;36""mtmpauth = $tmpauth""\n\e[m"
-      echo -e '\E[37;31m'"\033[1m[error]\033[0m" "Token not valid, requesting new one..."
+      echo -e '\E[37;31m'"\033[1m[error]\033[0m" "Token not valid"
+      (($verbose)) && echo -e "\e[0;36""m$(echo -n "$tmpauth"|jq -r '.error_description')""\e[m"
+      echo -e "Requesting new one..."
     fi
-    sed -i '/accesstoken=/d' "$config"
-    sed -i '/idtoken=/d' "$config"
+    # sed -i '/accesstoken=/d' "$config"
+    # sed -i '/idtoken=/d' "$config"
     REREGTOKENS
+    tmpauth=$(curl -ks -H "User-Agent: $useragent" -H "Authorization: Bearer $accesstoken" "${pod}"/api/openid_connect/user_info)
   fi
   source "$config" && unset password
   user=$(echo "$tmpauth"|awk -F'sub":"' '{print $2}'|awk -F'"' '{print $1}')
-  ! (($quiet)) && (($verbose)) && echo -e "\e[0;36""muser = $user""\e[m\n"
+  unset tmpauth
   if ! [[ "$user" ]]; then
     echo -e '\E[37;31m'"\033[1m[error]\033[0m" "Error validating login token.\nCheck/set your auth and try again."
-    unset tmpauth
     (($verbose)) && echo -e "\e[0;36m""Exiting.""\e[m"
-    exit 1
   else
-    if ! (($quiet)) && (($verbose)); then
+    if ! (($quiet)); then
       echo -e '\E[37;32m'"\033[1m[success]\033[0m" "Token valid for user: $user."
+      (($verbose)) && echo -e "\e[0;36""muser = $user""\e[m\n"
     fi
   fi
 }
@@ -294,6 +298,7 @@ REGISTER(){
       fi
       sed -i '/password=/d' "$config"
       echo password=\"$(sed 's/\"/\\"/g'<<<"$password")\">>"$config"
+      #'
       if (($verbose)); then
         echo -e "\e[0;36m""Password have been saved to $config""\e[m"
       fi
@@ -317,6 +322,7 @@ REGISTER(){
           (($verbose)) && echo -e "\e[0;36m""Exiting.""\e[m"
           exit 1
       fi
+      unset csrf authtoken authcode accesstoken
   else
     echo -e '\E[37;31m'"\033[1m[error]\033[0m" "Script appears to be registered previously."
     (($verbose)) && echo -e "\e[0;36m""Exiting.""\e[m"
@@ -325,8 +331,9 @@ REGISTER(){
 }
 
 GETPOST(){
-    VALIDTOKEN
+  VALIDTOKEN
   post=$(curl -ks -H "User-Agent: $useragent" -H "Authorization: Bearer $accesstoken" -H "X-CSRF-TOKEN: $authtoken" -H "Content-Type: application/json" -H 'Accept: application/json' "${pod}"/posts/"${postid}".json --cookie-jar "$cookie" --cookie "$cookie")
+  unset password csrf authtoken authcode accesstoken
   error=$(echo "$post"|grep '{"error')
   if [[ "$error" ]]; then
     echo -e '\E[37;31m'"\033[1m[error]\033[0m" "Did not recieve post."
@@ -354,7 +361,7 @@ GETPOST(){
 }
 
 POST(){
-    VALIDTOKEN
+  VALIDTOKEN
   jsonstart='{"status_message": {"text": "'
   if [[ "$aspectoveride" ]]; then
     aspect="$aspectoveride"
@@ -383,6 +390,7 @@ POST(){
   cat "$message"|sed 's/\\/\\\\/g; s/\"/\\"/g; s/\($\)/\1\\r\\n/g'|tr -d "\n"|sed 's/\\r\\n$//'>>"$postfile"
   echo -n "$jsonend">>"$postfile"
   post=$(curl -ks -H "User-Agent: $useragent" -H "Authorization: Bearer $accesstoken" -H "X-CSRF-TOKEN: $authtoken" -H "Content-Type: application/json" -H 'Accept: application/json' -X POST -d @"$postfile" "${pod}"/status_messages --cookie-jar "$cookie" --cookie "$cookie")
+  unset password csrf authtoken authcode accesstoken
   pguid=$(echo -n "$post"|jq -r '.guid')
   if [[ "$pguid" ]]; then
     if ! (($quiet)); then
